server:
  port: 5555

    
#Configuración de los niveles de log
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      pe.fintech: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: routes,filters
       
zuul:
  ignored-services: '*' 
  prefix:  /api
  routes:
    serviciocliente: /cliente/**
    servicioprestamo: /prestamo/**
      
 
    
    
    
    
    
    
    
    