language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - jcabelloc@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: IyLVi3z30wOKJWFdO6grtTKDZhLGI38VSiXYFvJXAG4GupGaBINtmZwVSOQ1rYL3mnVw6n5+ofgATE+qFFa0l6cSxpV6n3wEB1MGhiDXaQcHuzoAov4VZkFSg9ZdP+HDLukO3Qt7I2TWf7MPKs8G6E7onP1XvWJcNtdq1xmdiLAj4+OO4pmp2hwCdqmaV5BQtU6sb0yBm4ixmDMIaKcHMvJHKjaYmLD9Uw+6NKKNSMorlThTbL0jk9fMh7t7rxrOjedl+IxnHMmZ7cgB7w4nQgz6Erm1qWbZAe7Juba++5GMNqxvEabFx44Va5zQiGmxZ9SQDmDlVNe+WFGksxIg4ytT4cQGFFauUdTmrANEssLEGXPyFaMqBbCPSTqYT095OB1s0BTiJSz94omJhdmcAJRh9wCk73nr+/6rOfAstcUeW1j/q03oMpcz14bCtRbyW6wZDqjKYiKWWdwAZmepH8GBIGJopMFEbWsZUIWXUUM3cd0mzmW2EihvH0X0Tma4t6mNAdKQ65kDGu+Xxh47Aoz+PVuPdWGoOEiTKmBkc4ZzA6Lifzle1bI2k6RLxrRZx5Gcp8htPg18ABDNfeIVh7jPJnGqHYhcfCef7M+nAa7l5+GtaN5mljmq6eYhq/wBVw1joYTbG3O31HKqu/4n/ip2z+SKhStBATqgz1DEUI0=
  - secure: KIT74TYPG6ioW1RdKqDts2jM9FkilET4v1Q647Af0f5xcodL0o+54mNxfu5RSD4R2NezVImxfvqc/iQpKwiyz8uvDkgPmSaNZPNT1nPiQvSFxCADOon+tPYY17o/76T82AUqkax8nt1XFoReyF6ytmjJdWHSIvdLGNDuEEgPVsEoWjeVH7W47fCTjzRkqGhqkmp4hgYRUnSQIxUEWyhwB984xuLH4a9rTaP03MpPq95eOOvNtv97MqjlQyu1GcfrjOWpXqEPM9GIHxdTEIe7p55nHTYZXsH+M3uD9sv4E86+J7ujjLmCF6KvV33tRgHSia2RrQlp9lDclpGKR1aqmyQA/Ck5v0EO8HB0FGqyhu0tqSo3ZsSiYii79LnQks1W85sLlKHRUxSz0IOfZWpqms2/P79cyDJRJ+jnRSAAqfvg8oSmcptPuxViaXak97aV5pmW3GMxUeUCK9PLZ3lYQX0rSDwJavovIrXKYb8HIj9jTVNd8noeMWVaUNzqWnqGWn9PGEtL7/ZoquELA7VCue4jlUPKAicDSonu5gydTmbclIKya/ghZqG7ryTGDVqaQ1ctLPvrVsbsrAr3ypxx6ZtxFJgH7fD9XVNiFlwwghfHtpV5J6/H/tVzxPpsdmmZIn5EkEBPJlDpmzp1MFANwc/Kc5LoQM4CWubh0u6FH8Y=
  - secure: K9xoL6fFdY1r5eQ/bVTF6JBetX3xLkwcU+HmbQfzlDBdL9AfDpD+sDDhaQL4X6lqh4oELgcZ8/EUT0cDLgLTzDdVZ4WYaer/rKckBrxb4rJbDchMt6+smgB8MRB0HuopPTjLqg9bDOqFS5lmcSkiYeFxp5A2K6B6+FIHbO3Yb0p3eM+CGVNDw0kM0hO2XN8FuEk1opQoL409KPxqW5YZFODWiIyPeKVllo9x04pHfJeBrcwCAwOpFyvgk8spSru7hPVo23bl286Wr5cdb55IuPjyTlI4D8WvdCWJYMTP1JzfTYV7SZCxyEuS8mwplHe5tksiuEzpmDFSCZqE0d3jddrI+aFkrzDcg5l2YSzfeKT+D/+6WZIYcMYk1NkJ309VvS74L3S+13kXPaRowbLYyXYKFr3DzeEsZ4L6K492M/9IeVLjZvhm/OGkfWy3uFAYLgARpAaoIjiSelEOT2adlKBI+sjVjsArMF1xlYsxDSvLnWcH6+9GegZZy1Tt2hlCLf4XpO8G0d00YQdTg5PaQBntMLwrcdI3Yx8f0kN6vS2/AX7YiwO8fLCqjlw9HMFZENWyZg5MTgKF29L209jVHCvVrxRZizVmSVjoeEZewFxTXzbqsO5arfEPp8UEeGvh45IkVbpEHIKyRhP8bxoZc8EC/jtPppJohgx2PYLsx/4=
  - secure: BE6PKpfB95a/jIXa+k8Rx3lz8VWsNXRaOGvev9ckJ/wM32AbrfonINQ5yPzdZTdV33GQ8i94LOTeqYNK8MCENKUJusRIIMF5uzHxVs8DvFku1aC+pyD4h+dYYYCZTXY/1RV+eKU1YIIHPoK36lZOyp1uVTQSTSzOrQnGyho6tXnZT5Ti7WHnx/754//gmG/r8Bkvdx8KVPuBiNFMgB2H8cLNHywcuSETOGuRwhI8GzhWrHnsNpKParzHqAlM9dREILghL7jTcK6npSHygChspzTkdOb7h1vIF1raB8hDx8SFxVBejSSz4eGLukERGRxHKMQhms9U0pEYRZ/7D0l3rWxfN1giUaZECrsRlsfm/CHItLlTnGbEjETkQmU56rOl4F4poyCzj1hvmmcGXj9hvVyt0HkiK8AGxIt0XmWjooqJkg/dM0+wJtkqlgHBNT8qC0p+QQ/kT/Clms0iYSCcPCdqwsfaRStzVrHNT9wvgk6Kv2BhgIjDMgCOc7f143V3LPp9l7ysJhA51v+MJ8rELtDt4G3I6zivu5k+OA4E018IQzEqHmS+SYulv4mXGsjQyZ8cEYPebIiWZ9wxMPRAwbBVmBoQsscA7/7Pmj7X5Ad66B4zGJRnZCVpQtQw/2JhRrXGr2qWUvSYM5+mOhbK6dlPWJ4Z0a7HueozjPoiU4o=
  - secure: FXaHpuZakISOVlUs1QLB/zvgdyxj9TvgX2+5v8xgTXcm+CIwfPLqz2vrDC0atKN0qdJhtWuY2ODs5l9TU5p1J6D0P9nMtlu5sx3SO/91HtvPcn6knnTW7JKDX5W/BhZV+mGOQhPnDYV0oS/U9DHIauOBP3zkOBfuTAfHwJNEDo5uvHpYKx7WglTIkhsqMLHIv90NEIcQHxbNW+2QK/DR0xBjPC23jyyeOcsQ8jwLgFMKHWcQL/XLJ2T8YOH/7852/NT9Km7GptD0/5fHJwK/nGtb1LyJ2GFo+CSWc/Ykyu7ePJVKyrRKnbnooMmtjnUIQZ8t2GqIp8U2N3RjWKj9hDkQp/WxKWJdKhdJLL/mRUBaCza0nwSveUW+72p//dhT0G1uecJh1zK8HwNxU+LIzj5sd57Kf5F3czS4KwgGXBDQ8sqlnbYpBt3n6MfT8D+ZpcPbiqaTacMcx7BfUFm6luskOgQPyMLpg4YUdIGrQPYUdqDCKMgRdHmqQX2SPyynEVJLX/hwEwEg+MyeDoNk7G2DgWsr9VWtAvDODvZKYnNnv6FFextxLDf0FDy/Wd8J/xnh+nvv8qLg/MDY6xu4A/ezEOpJBNiRKsg9x4Agjy0KIeeTlKN22+E/OxUCsiyqo1GBupvkDbG3VLlmlCOK07ewnmmB/5ytFjueE4DTl3o=
before_install:
- gem install travis 
- sudo curl -k -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=sms-cap-10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=54.186.143.169
- export PLATFORM_TEST_NAME="sms-cap-10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
# sh travis_scripts/trigger_platform_tests.sh