language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - jcabelloc@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: ia9YopPXpUKXv8LK6VYgxdNw6p7PC/ciml7KLzqhHLs+dDuUTfxcTMkO9JLQvsV9cvubI7OcIDwnM4WiQ+nkEP8+ALUSEyAJkWbw7qIfspW4rv32c48P9mvVgYGRQFipvkaIqk+i7fSscanJ7Zzk9+VYqIg5S4oD3f3YWUTxGX+Yc4KLU5nvdTIr33he2VHU+FKEwUvzDK55Z6xGe+Q02qAvlPbmHmeQXIxpkrQblCeNO2LHxWUsrvtA0BWZLe8zsEpflneiz+zYqKw57poHU/zMhybIv4QuJYVSJOzVZ5qjNZcrRkoyGnbDpwzNe7zeW22SLXEMULKoNYHBD8eX+4IWDZ6CqHztBycHtri/WA+/EeMVC8g0qrhdZNbdspYrmaFOjJMokRaxpbGygteZD7pSKbj7FBYAN15HQImh5zq2bUM/flMYYAdyEhFp46ygLKnIkTiZs2hlVOfLF3uqo0flLQA+SUmH+Sc24VMTGYCiq5YTU6HpBAbCpLyam9PpQxEqyLBeO2kNQG7mnn561K20SvOjzT7kAzGGgH+ksTDsx4vcnsJQiqoCjJSjPmJy0mIjtdqOoqGVKC4wJcT3YiT0/HBFEv5vpz5BbBbHNnaSTPXkYTMGq1qgxsppKbTi4AIVIG1DrZHbtPNk01J2iJdMgl924N8xwwOsL9M5wx4=
  - secure: hs5eka0d8oplShNHnkV+utOfk7SKOJUgtskjJRyXnaxfANttdUZQBH2aTnCnIG+Y+K+l603RLJuHscqghyFCB05KECgumvvlvI8WGxrewrf2uwRXpP0KNoFwdOSKPhEGCpsuCjczDy+h+p5H6fyheM+vLktq6AZQhCmGU7oQ2Oild8hSc5YCo+21hXvKDqtHzZgCrbjeS+D+6RVySHoF2IDAJSNHTAj3QIcX41BvY5GRphm4oNCXTIeANKszHQAxVGaIM+LoOsd6+7DeglKkYTh/2dWVHmDkU0ACkcw6tJBq36av4QsHvB+SuBwR1lzzNOjTXxNEqgY4GdzRIcUUFs3ItKAUukpgZibqSammnQo9SYXEHSdn+2I+wqi+yGuetm81wp4kfs22g/N+kfn8FIjY4ET05fczJz3ZiPlziYhjsQFFLqdYURCacEYpI5aAdY0MYaR3JT8D5mWTHCbxqxFzsV9tKvpgEcAEfEPiu3NSih+IxWaSySFFFDGNQU/g06fJHpFK94Dl/ctxinQwx0bhWOmkc7iOWVaKz5DOG+6f6pJHw5syYU2WkXInwwogNDm7qnvOYnWCclhFwSQGgyH1wHRz+O+Q6b+m7+ETyynI+2kXGqYEvy1l9Cm0BhkFLzEeSEWRAT2KmQ4fLSPtVdd0smIhqHvUGPvbc2gSoeA=
  - secure: ebohrcMW5ITH0defXVFJxYtZ2Wz0uo6l/K74O3Y/TbBS3nRb4KSpoBZBmqKjVxJJlazTcFGQUdsFnk+8ObhWhOYrAu8r0ee8OKNFw5WyUqIFxgzK1Lp04fJ+/qfLvdAmh+v6wRhGnj1NSf2Cn5JxVNNhf8m2aAxGM/e14SwbC01V0UpEJaYMj0ab3clmZtCNtQ7Z0eGO75vbb9YFk0qd/bkiHz/pNOgwSjSd4S2FB9/SvLOVPeY3tSZgBnn57EvTIGjwhsqRoS4KP8sC2QHNSLXvDU0IE3eypvhhLurVoCQ43TCIzxv9QKnWvGrpxfzebkiq0DGeuphxh25mzg/Ul+Z9Qv18XF5zt/AJndyPgh3Pk1WmJFjxsjmPDV+klPEAm9XuZUHLabpyMSdOzm1FBuwrqe7J9A8aZDJGvj9Sor6oHOGC20CmMZalf/jHSAIkFo5zB+QFPb4mznahE/RKOKgUBS2sPM8ep0E3b1HYxtO3xkJxlKv/byqbtHCn2cs3q7F772iRH2tTjKqZPagSe2nW0FKG/FI4Z+lDWc+XACTcM60ifj+Bzl2qHCP193k6xaCRIn2xDLi2wV58zaRu5EfAbOHxZ284/Tt45bfjCfomKqgOhvqdMy3Mr9Iug8cQyCddVyV0qrvKGNNIfxn3KFpNf4hNjkRfZDoNrGzQIVE=
  - secure: ayoxbtr6TuK/boh6O6m/KEUxmR1o5kqWRlpZFdOhAlLSaETpZIX7gfkKrSMSJs+b54sqD7v6/HD2J7rIIkoTa2f/8u766iZ4nciI8VrltnDalKy5nwwiZFGVNvPkKA1zc0V8dYleYSKGn0Wlc5a1jJwzc2Imo4z6DKqLUVUuHcf/v9e4FGDvOb3fXFILef93IJoIaNtZN0eWPg1afCwC/46PfvK9kFVId+NXsLISR89OEaVCtYkhgUwVD97Zh1huG49Vpm2xp3eSxhAplNPwdsct12s1ZRFl1T/E/S7iyztKiYJxZ6x4vT7EL9iQFFjqnEcLhOjt+miXXKNNJHW+ha//+//enRcPqrQ6JLiiK2MJcbK6rdothVH4vCgdjGTMvcUmKB70O3gk5K5wqG1AQsORLDUEmh7z7iTHxQcMtDMGB/uM38x4eR9BhUGmrrpyVK+KhLsnQOhGI0qW3chqmTfN6U4ypRHwVJpQdKjypu5kgNpMnZnbLpfRw2ma9cJ389fpWpmOgk7V4GqYmDKV4mu1qT/U7iQ80qT4JVKB6yfm73kxZr0f30hZHFRhx7uO7oJzM6G4shPQ94Ofwbt5rr5xIuwhDoRkQ7qVdRnIts1OwHxlfiuv190uWJGEElKl5AIhZJbAGbqqnwhZQ/8oYTGsgkGK6LV4JvY8f+Kt7YI=
  - secure: ttMbVqcZkxoBFCi3E3YMhUYx/CF1TzG23dZqmSei4WSPDE3201+Qt4D/lGqKeG69Zz0BuoedrTvZdum9we4Rd8xIvBz3j86HUDmVp2Qz4GgXkbzDYMnMSuO3whi4+zM6qEHJwhmkScpO/E2ZMvUjQJ84MbwkpUSEobCtNTS+/kBvzrch1OLLpWPQ0SEpuElXSvu/jUExqU0VylECPStcjwsiW1+6P80KuNTLcAYA9Y8j6sGXpXCYydUUQWaqXx8HHAPLVBseReiSZtTolZLsg4064HhyuREjeNNgAvbxJ7+ZZ9OYMRAEuaiFXXTvREFxLaNgrXwIwr314So7VG8/K+z95CcRSociI3k/7K/9sf63kJLt+vlZh7Vn32EpXgA4pIFWbvLBmUKsUZhovr6dIhYp0mnuI2/+I4HLZSSch8vLUKIxb6C6/qhs1ouQXlM29RyCJeXQbPUUoVFCFuTRC+8m5DJTrQyQpGDneRbRf3AbQIZb7a5lHOMOnehWya2W+Xf3GXlozX9rOSnEcEtOjXaV4pjWPveh1SnVxB9t0VN0nCmAYcUL2vYDkWI5pxQiP2tYfZsirvpYF4n3q8Bkn+6rqRSeq+ocTrEBINOSXqbRd6YDTtgzqDlfTsw7MShqcUAucFyITY0GeV5b7S2IM6oysdswcuP9J+7LmDBt3A8=
before_install:
- gem install travis
- sudo curl -k -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=sms-cap-10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=54.186.143.169
- export PLATFORM_TEST_NAME="sms-cap-10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
# sh travis_scripts/trigger_platform_tests.sh