language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - jcabelloc@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: xaz28A+CJ4FrGLbX9jDDaofqBM4OuIrFBcOHyn0YwHMzCF0yiPqkUGkqw5ThEVNRCm7d74LxuqMutT9jADwhggRDYbX1bjdmhh+eKiIfinc/EEj3LjeOzHENe+gbyvzdUeNRn8E1pgoFwQCnXvyYnOfnQl80aJD+Gon+aQIvuSKp3Q4vUf/XLpdd3bgjitoZ/0kUX6pwyR/FL2AP5G4LkuxOKFU9TYCBBSvqs7yQGmWlq7TxXKp/l91Wstaq4hpd2yUXEBDwYXeaZswlYgbHehO/Vnfzt/Va145A4SwkB5A7y0uCPwx7twYS3SRiIEsQ4+oL2T9vPJWwrSnpbu+oIvXwDQ4LXWa5pGfBYOCiPqJ297i7tDcn4N+bVE4/tl+F1YT8Zc+hdyztXLLj5nG2tBAnMYQqERnJB1JaQjFXCD6EpWVvZxCX+hF8gS7VlhTSfLlecLhVUDqoguLvqzqZ7o9dWrgm6OQ7aOPEwjAvgERzSWxmrwjxmW3trSBirdFm1ltRYWtOEcl/4etYfpVnWYu6Ixdesb51TRhDSRqAxWp+f7HWOd0BLDyxiuOj4lBNCZcM4PQpTRxZbzfRYjrSl03MV0iniGiGErUK9ZVZ4itAl6dQl4ruk0Jba+nOyNcjydCKeFtAiYs3HPEXl//b+P/yumAYMAwYZWIL0d3qMhY=
  - secure: PJNA7RMZfptbOtUDIZFD1pShCP0ijqW5iqtQGZ2mahvfFe17jLnbTui1oXlK48poiPKVkbF3gcQkyOSuKIFJyvweZQimF+pvaXOXvm/Yu1wMBo9Py906p6olsxgfyVC+BnR7V9TKchZArdcsiiEch3pxs3z4tV8Q/LQS0CpfdvA1Q3NVJr6a3gw/yaJSqi2g2lD6f3Ueo9LPHP+Mq+ldIMxwRkMBGZfJaEIGIBx/xnRSFQ8kjDr6DcDm04SkwDCE3McSpn0zYweqlh6fOFkibT+aNIHasxB6Iv8iIyGU9WostLVTZyZsUhcCBgpG4/8lC1s2ZUiPDTkRPbQhR9uAWb4w6sVvZr/gwsrKyvbOBzwuj0yRQwVHATJLRCYy91ZgQdFg2FZcTfCsYeHxgw1ykQaBTXdJOj6Uf2CLgGXv6lnyavY19M+M35FOioX2TRCgf6qH9Ifj2wwFRlksd0uGDIzyGmvgRhG2iUEc1eyEEv+Y8KgHyPhfx1Y7eNaAs0Vln20F1T1O54xQRIRGxoLimd7r1IqN5QyFZxjGitGpF3QfBjtM1V1KhtfXnBuPmd9famwj5BPmauty5ZvLeOUggEunSzYEQl8sd8qb9z3QHjOimbxm+ylu9ZhJH6m4PdSpaWsyvIIw19PheVOqFxot+Z1kM/NOMQNI/PYwnjUBazM=
  - secure: dr8nkd88WwnlUVZKlXK7c5tFvE1yi/Xgc7btGxHjomHvzIO/nrGjHhabKuwRKR9vaH/xpVofXWTN7/A0DRABCVoE/z4OKke3/8m4H6TRpfMuTsWRumJTozXbRt1LBvhrd9BWHUv73z7kN87XIjj4CD3fmb0Jz4rhUhd4cjHjZV+OAetVq1By6xzcra7r6n73fErJ6iQZDMQ4YKBHV502rmGASubBdKZoogTnOJZJBc1r6DM8s1PnyS1JbQpBy5ezEqHL0f0NuyT/f+zLlloIlorakj8Eg445r8jgDjIVlNq3po7f2VBXKmBQ3k7xQetkUyaRy2iZEI6e9VP++PqPJlNEzcgJJzHcJTJLeQ3Dj9Q10HKl0bayL/uquZxYLHdaDndBXgikmqcd14Wy8TPbQjZVj/TZDPxH2jyWHKZxJBFZRcLKAxBGyMFmkEFYs+etbiE+0Wc0jkYq/sRY2tTdwaX7u4r83T/hXAyc3iQQJrofHKMqw+9TUBDCCJ5iqjdHA/qUN1O21i3JlRRLOHwP4lnSCbvh8xVnZCPhWsc2NR1czhJ3Yy+dQk3jL4hAWBiDXAeGrhukU+Ie80em1h3eCC01csy+Rbr/f1QZmJvv3VlFSndtaD8vr+NR0Jv5H+LkL12uMDJPiNujGk8yi2zeN2dGpJshay24Bbr2lQHeqrg=
  - secure: j45KS66UZDarx/nIrPq3cBlJXo34FHyM0ufXHz0fMPDEB8JqXU+HPDQu58MMHDvz7FKjKRuF3o/t4BKynO5qPyOuaoROq6UTqhcCAxEtftDxRu4P62DYlj9H5jfV1UGgjae4ujb1bFUDeHmx8ut/63Qpp7TiYJIOQlwOMsSlW6tT5zoPiH1SsdlLOBYBPQ9+NXDMJTNUxd2uXeNNIHFbD6OczEXnSNF/yszfV6ETuy2XBziAz7vXgufema6wDUEDzmFW+LjhlXzjJ9XWbovNYOfQdANDErZBC8BVlNxnueA9zoT4UEI8dA1MsnGK2Qb6SjARlrBxsWnnjTUAwPu400bDUC0Gdz1WEmA5ZLmJx9xN20m5vuevVWoAmiS12CHZduljlLElTWqmBnWTOcgvZW6Ht0jUw9K5iveRWDnPAnlF69GqLzdZNHQED4qxQTqeQfy1PIkGcu/x9TVYfjTUeTDYC/QZTPjgLm/2qnM6s/vXuavjUuvY3ibJh6nH0JC6RUWa9M63RyuUo/HpVazkrqqlA1dYWkKNFWTeBPdpeXsGM+oG0J+J+fSCFeujns7amf1w+/SZsBJNnZX8kEVmgVVC3OaWv0V6X6dCraQnkgzDo/NHdazPkQu3xvsPZaVx+rwzuqTdJEQECTAwRs5yzKKrrEPOj1SsB410SQJIHaY=
  - secure: PuHbzIb59zXZMoapEB1okFGDc7pLJceYYfwInDEJdKgSFUV4FvI4RqltNiBRr+UTZi/zyuqICq0xQcQeR1l/zmOfmG7LD8Mp7RwsY06vS5Dhy/u5BZAbOssoy74+EsXDQDrlxRFzAv+6gx73TUpmM1XasmTKjyj2Ln6yazdPLjWaAJvcwbx4CHunEzh0g9/Rg3UgiU7zaKfwygrgi3+QlfS0CYy99/KIQwCe65ohe9l4dEKUplG1ihmo7cLjCGIUeaqK1PCWmXwJLO1aYsvEKCXX95eBUKiuU9qcve+gci9wAzHu+pzf33kJd6I4r3Q55cB0A4UG1uNY7NyFE8UqdJwvJfyDLkZQyBg9EEKf8Y67sAjAHzI0xNnDL2wfJlNsJdCJiycHETE9+eprVUKzbXwXCzHfr39i5pL92EUCcuCmgcamnf2Y1mIR/8gn2a7s3wCMf43I1GcpplAc06S3uSgmzYnrIeeUtbR5JE3bhxTxttMCf0aIfzLEQMbO8i2ds0zuMkFb4Cwf4Vm6mnUHbBQuhK4t0gEgGHwEXwB2dqYVxUwn42rW2pORsdv3DC7ib9QUZJRPO5HIimI+pPOFQLLNCqiWYIVpE7xMZUraioEAn5aLYFeWW3l1GJLy8IhbAxuyiopUk/LcPx7/cUIwKKeHxTOknUZlhmdRyx3jYAY=
before_install:
- gem install travis
- sudo curl -k -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=sms-cap-10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=54.186.143.169
- export PLATFORM_TEST_NAME="sms-cap-10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
