security:
  oauth2:
    resource:
       userInfoUri: http://localhost:8901/auth/user
       
server:
  port: 8085

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    pe.fintech: DEBUG

spring:
#  sleuth:
#     sampler:
#      probability: 1
  cloud:
    stream:
      bindings:
        output:
            destination:  clienteChangeTopic
            content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost

          